### ISSUE TITLE
@conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by mathbunnyru** [conda-forge/r-devtools-feedstock#30] opened 2023-02-06 22:50 UTC
### Comment:

I get some version dependency bug with this package under Linux aarch64. I hope this will help.

**Comment by mfansler** [comment] 2023-02-06 23:11
Could you be more specific? This is a `noarch` build, such that there is no compilation nor direct dependency on pinned libraries. So, a rebuild is unlikely to be the solution. Perhaps the metadata needs updating?

**Comment by mathbunnyru** [comment] 2023-02-06 23:15
I got the error here:
https://github.com/jupyter/docker-stacks/actions/runs/4101767597/jobs/7089277765

This is the Dockerfile which was built:
https://github.com/jupyter/docker-stacks/blob/main/r-notebook/Dockerfile

I tried to investigate which package gives an error, and it seems that everything works fine if I exclude `r-devtools` from the build.
Moreover, x86_64 build works just fine.

> Perhaps the metadata needs updating?

I don't think so - we build docker images and always call `mamba clean --all -f -y` after calling `mamba install`.

**Comment by mathbunnyru** [comment] 2023-02-06 23:24
I will investigate the problem (but not today); the problem might be in some of the downstream dependencies.
It would be nice if mamba gave more information about what's going wrong by default.

**Comment by mfansler** [comment] 2023-02-06 23:29
Immediately, I think the problem is `r-gert` is not built for `linux-aarch64`. The latest versions have the dependency chain:

```
r-devtools -> r-usethis -> r-gert
```

I'll look into migrating it.

**Comment by mathbunnyru** [comment] 2023-02-06 23:30
Thank you! 👍

**Comment by mfansler** [comment] 2023-02-06 23:43
There's [a PR to start the process](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4063)...but `r-gert` has had problems with Windows builds recently. So, if it's not super urgent, I'll try working that first. If I can't get that working soon, we'll just temporarily skip Windows.

**Comment by mfansler** [comment] 2023-02-07 15:04
The **linux-aarch64** builds for `r-gert` [went through without a problem](https://github.com/conda-forge/r-gert-feedstock/pull/29). Give it a couple hours to get on Anaconda Cloud. Not sure if that will be sufficient, or if other packages also need updating.

**Comment by mfansler** [comment] 2023-02-08 03:57
@mathbunnyru there were a couple other dependencies that needed **linux-aarch64** builds, but they're building now. I just checked a solve and everything seems to pull the latest versions now:

<details>

```bash
% CONDA_SUBDIR=linux-aarch64 mamba create -n foo r-base=4.2 r-devtools

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['r-base=4.2', 'r-devtools']

pkgs/main/linux-aarch64                                       No change
bioconda/linux-aarch64                                        No change
pkgs/r/noarch                                                 No change
pkgs/r/linux-aarch64                                          No change
pkgs/main/noarch                                              No change
bioconda/noarch                                    @   2.1MB/s  2.1s
conda-forge/noarch                                  11.1MB @   3.8MB/s  3.2s
conda-forge/linux-aarch64                            7.7MB @   2.3MB/s  3.6s
Transaction

  Prefix: /Users/mfansler/miniconda3/envs/foo

  Updating specs:

   - r-base=4.2
   - r-devtools


  Package                               Version  Build                     Channel                         Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  + _openmp_mutex                           4.5  2_gnu                     conda-forge/linux-aarch64       24kB
  + _r-mutex                              1.0.1  anacondar_1               conda-forge/noarch            Cached
  + binutils_impl_linux-aarch64            2.40  h870a726_0                conda-forge/linux-aarch64        6MB
  + bwidget                              1.9.14  h8af1aa0_1                conda-forge/linux-aarch64      122kB
  + bzip2                                 1.0.8  hf897c2e_4                conda-forge/linux-aarch64      405kB
  + c-ares                               1.18.1  hf897c2e_0                conda-forge/linux-aarch64      121kB
  + ca-certificates                   2022.12.7  h4fd8a4c_0                conda-forge/linux-aarch64      146kB
  + cairo                                1.16.0  hd19fb6e_1014             conda-forge/linux-aarch64        2MB
  + curl                                 7.87.0  h6ad7c7a_0                conda-forge/linux-aarch64       89kB
  + expat                                 2.5.0  ha18d298_0                conda-forge/linux-aarch64      167kB
  + font-ttf-dejavu-sans-mono              2.37  hab24e00_0                conda-forge/noarch            Cached
  + font-ttf-inconsolata                  3.000  h77eed37_0                conda-forge/noarch            Cached
  + font-ttf-source-code-pro              2.038  h77eed37_0                conda-forge/noarch            Cached
  + font-ttf-ubuntu                        0.83  hab24e00_0                conda-forge/noarch            Cached
  + fontconfig                           2.14.2  ha9a116f_0                conda-forge/linux-aarch64      280kB
  + fonts-conda-ecosystem                     1  0                         conda-forge/noarch            Cached
  + fonts-conda-forge                         1  0                         conda-forge/noarch            Cached
  + freetype                             2.12.1  hbbbf32d_1                conda-forge/linux-aarch64      639kB
  + fribidi                              1.0.10  hb9de7d4_0                conda-forge/linux-aarch64      116kB
  + gcc_impl_linux-aarch64               12.2.0  h0c671d3_19               conda-forge/linux-aarch64       54MB
  + gettext                              0.21.1  ha18d298_0                conda-forge/linux-aarch64        5MB
  + gfortran_impl_linux-aarch64          12.2.0  hbc5a9e1_19               conda-forge/linux-aarch64       14MB
  + graphite2                            1.3.13  h7fd3ca4_1001             conda-forge/linux-aarch64      107kB
  + gsl                                     2.7  h294027d_0                conda-forge/linux-aarch64        4MB
  + gxx_impl_linux-aarch64               12.2.0  h0c671d3_19               conda-forge/linux-aarch64       13MB
  + harfbuzz                              6.0.0  hbcb8a4f_0                conda-forge/linux-aarch64        1MB
  + icu                                    70.1  ha18d298_0                conda-forge/linux-aarch64       14MB
  + jpeg                                     9e  h9cdd2b7_2                conda-forge/linux-aarch64      484kB
  + kernel-headers_linux-aarch64         4.18.0  h5b4a56d_13               conda-forge/noarch               1MB
  + keyutils                              1.6.1  h4e544f5_0                conda-forge/linux-aarch64      112kB
  + krb5                                 1.20.1  h113d92e_0                conda-forge/linux-aarch64        1MB
  + ld_impl_linux-aarch64                  2.40  h2d8c526_0                conda-forge/linux-aarch64      739kB
  + lerc                                  4.0.0  h4de3ea5_0                conda-forge/linux-aarch64      262kB
  + libblas                               3.9.0  16_linuxaarch64_openblas  conda-forge/linux-aarch64       13kB
  + libcblas                              3.9.0  16_linuxaarch64_openblas  conda-forge/linux-aarch64       13kB
  + libcurl                              7.87.0  h6ad7c7a_0                conda-forge/linux-aarch64      361kB
  + libdeflate                             1.17  hb4cce97_0                conda-forge/linux-aarch64       67kB
  + libedit                        3.1.20191231  he28a2e2_2                conda-forge/linux-aarch64      134kB
  + libev                                  4.33  h516909a_1                conda-forge/linux-aarch64      106kB
  + libffi                                3.4.2  h3557bc0_5                conda-forge/linux-aarch64       59kB
  + libgcc-devel_linux-aarch64           12.2.0  h58a5bb6_19               conda-forge/linux-aarch64      279kB
  + libgcc-ng                            12.2.0  h607ecd0_19               conda-forge/linux-aarch64      541kB
  + libgfortran-ng                       12.2.0  he9431aa_19               conda-forge/linux-aarch64       23kB
  + libgfortran5                         12.2.0  hf695500_19               conda-forge/linux-aarch64        1MB
  + libgit2                               1.5.1  h8cfa638_0                conda-forge/linux-aarch64      942kB
  + libglib                              2.74.1  h01e6fbd_1                conda-forge/linux-aarch64        3MB
  + libgomp                              12.2.0  h607ecd0_19               conda-forge/linux-aarch64      466kB
  + libiconv                               1.17  h9cdd2b7_0                conda-forge/linux-aarch64        1MB
  + liblapack                             3.9.0  16_linuxaarch64_openblas  conda-forge/linux-aarch64       13kB
  + libnghttp2                           1.51.0  h674c3cc_0                conda-forge/linux-aarch64      671kB
  + libopenblas                          0.3.21  pthreads_h6cb6f83_3       conda-forge/linux-aarch64        8MB
  + libpng                               1.6.39  hf9034f9_0                conda-forge/linux-aarch64      299kB
  + libsanitizer                         12.2.0  hc13a102_19               conda-forge/linux-aarch64        6MB
  + libssh2                              1.10.0  he5a64b1_3                conda-forge/linux-aarch64      248kB
  + libstdcxx-devel_linux-aarch64        12.2.0  h58a5bb6_19               conda-forge/linux-aarch64       10MB
  + libstdcxx-ng                         12.2.0  hc13a102_19               conda-forge/linux-aarch64        4MB
  + libtiff                               4.5.0  h4c1066a_2                conda-forge/linux-aarch64      453kB
  + libuuid                              2.32.1  hf897c2e_1000             conda-forge/linux-aarch64       31kB
  + libwebp-base                          1.2.4  h4e544f5_0                conda-forge/linux-aarch64      437kB
  + libxcb                                 1.13  h3557bc0_1004             conda-forge/linux-aarch64      413kB
  + libxml2                              2.10.3  h249b6dd_0                conda-forge/linux-aarch64      818kB
  + libzlib                              1.2.13  h4e544f5_4                conda-forge/linux-aarch64       74kB
  + make                                    4.3  h309ac5b_1                conda-forge/linux-aarch64      497kB
  + ncurses                                 6.3  headf329_1                conda-forge/linux-aarch64        1MB
  + openssl                               3.0.8  hb4cce97_0                conda-forge/linux-aarch64        3MB
  + pandoc                               2.19.2  h8af1aa0_1                conda-forge/linux-aarch64       14MB
  + pango                               1.50.12  h1f1e9b3_1                conda-forge/linux-aarch64      449kB
  + pcre2                                 10.40  he7b27c6_0                conda-forge/linux-aarch64        2MB
  + pixman                               0.40.0  hb9de7d4_0                conda-forge/linux-aarch64      551kB
  + pthread-stubs                           0.4  hb9de7d4_1001             conda-forge/linux-aarch64        6kB
  + r-askpass                               1.1  r42h8e445f0_3             conda-forge/linux-aarch64       31kB
  + r-assertthat                          0.2.1  r42hc72bb7e_3             conda-forge/noarch            Cached
  + r-backports                           1.4.1  r42h8e445f0_1             conda-forge/linux-aarch64      115kB
  + r-base                                4.2.2  h620ca72_3                conda-forge/linux-aarch64       25MB
  + r-base64enc                           0.1_3  r42h8e445f0_1005          conda-forge/linux-aarch64       47kB
  + r-brew                                1.0_8  r42hc72bb7e_1             conda-forge/noarch              72kB
  + r-brio                                1.1.3  r42h8e445f0_1             conda-forge/linux-aarch64       43kB
  + r-bslib                               0.4.2  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-cachem                              1.0.6  r42h8e445f0_1             conda-forge/linux-aarch64       76kB
  + r-callr                               3.7.3  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-cli                                 3.6.0  r42he0e9005_0             conda-forge/linux-aarch64        1MB
  + r-clipr                               0.8.0  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-commonmark                          1.8.1  r42h8e445f0_0             conda-forge/linux-aarch64      161kB
  + r-cpp11                               0.4.3  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-crayon                              1.5.2  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-credentials                         1.3.2  r42hc72bb7e_1             conda-forge/noarch             188kB
  + r-curl                                4.3.3  r42h8e445f0_1             conda-forge/linux-aarch64      724kB
  + r-desc                                1.4.2  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-devtools                            2.4.5  r42hc72bb7e_1             conda-forge/noarch             431kB
  + r-diffobj                             0.3.5  r42h8e445f0_1             conda-forge/linux-aarch64        1MB
  + r-digest                             0.6.31  r42he0e9005_0             conda-forge/linux-aarch64      192kB
  + r-downlit                             0.4.2  r42hc72bb7e_1             conda-forge/noarch             122kB
  + r-ellipsis                            0.3.2  r42h8e445f0_1             conda-forge/linux-aarch64       45kB
  + r-evaluate                             0.20  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-fansi                               1.0.4  r42h4fed366_0             conda-forge/linux-aarch64      320kB
  + r-fastmap                             1.1.0  r42h526691d_1             conda-forge/linux-aarch64       73kB
  + r-fontawesome                         0.5.0  r42hc72bb7e_0             conda-forge/noarch               1MB
  + r-fs                                  1.6.1  r42he0e9005_0             conda-forge/linux-aarch64      495kB
  + r-gert                                1.5.0  r42h3bc7211_3             conda-forge/linux-aarch64      193kB
  + r-gh                                  1.3.1  r42hc72bb7e_1             conda-forge/noarch             104kB
  + r-gitcreds                            0.1.2  r42hc72bb7e_1             conda-forge/noarch              99kB
  + r-glue                                1.6.2  r42h8e445f0_1             conda-forge/linux-aarch64      160kB
  + r-highr                                0.10  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-htmltools                           0.5.4  r42he0e9005_0             conda-forge/linux-aarch64      355kB
  + r-htmlwidgets                         1.6.1  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-httpuv                              1.6.8  r42hc3d7334_0             conda-forge/linux-aarch64      791kB
  + r-httr                                1.4.4  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-ini                                 0.3.1  r42hc72bb7e_1004          conda-forge/noarch              32kB
  + r-jquerylib                           0.1.4  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-jsonlite                            1.8.4  r42h4fed366_0             conda-forge/linux-aarch64      640kB
  + r-knitr                                1.42  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-later                               1.3.0  r42h526691d_1             conda-forge/linux-aarch64      131kB
  + r-lifecycle                           1.0.3  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-magrittr                            2.0.3  r42h8e445f0_1             conda-forge/linux-aarch64      222kB
  + r-memoise                             2.0.1  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-mime                                 0.12  r42h8e445f0_1             conda-forge/linux-aarch64       54kB
  + r-miniui                            0.1.1.1  r42hc72bb7e_1003          conda-forge/noarch            Cached
  + r-openssl                             2.0.5  r42h38a8ed3_0             conda-forge/linux-aarch64      636kB
  + r-pillar                              1.8.1  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-pkgbuild                            1.4.0  r42hc72bb7e_0             conda-forge/noarch             190kB
  + r-pkgconfig                           2.0.3  r42hc72bb7e_2             conda-forge/noarch            Cached
  + r-pkgdown                             2.0.7  r42hc72bb7e_0             conda-forge/noarch             722kB
  + r-pkgload                             1.3.2  r42hc72bb7e_0             conda-forge/noarch             199kB
  + r-praise                              1.0.0  r42hc72bb7e_1006          conda-forge/noarch            Cached
  + r-prettyunits                         1.1.1  r42hc72bb7e_2             conda-forge/noarch            Cached
  + r-processx                            3.8.0  r42h8e445f0_0             conda-forge/linux-aarch64      345kB
  + r-profvis                             0.3.7  r42hc7730c6_1             conda-forge/linux-aarch64      195kB
  + r-promises                          1.2.0.1  r42h526691d_1             conda-forge/linux-aarch64        2MB
  + r-ps                                  1.7.2  r42h8e445f0_0             conda-forge/linux-aarch64      328kB
  + r-purrr                               1.0.1  r42h4fed366_0             conda-forge/linux-aarch64      489kB
  + r-r6                                  2.5.1  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-ragg                                1.2.5  r42h09301e4_0             conda-forge/linux-aarch64      427kB
  + r-rappdirs                            0.3.3  r42h8e445f0_1             conda-forge/linux-aarch64       54kB
  + r-rcmdcheck                           1.4.0  r42h785f33e_1             conda-forge/noarch             180kB
  + r-rcpp                               1.0.10  r42he0e9005_0             conda-forge/linux-aarch64        2MB
  + r-rematch2                            2.1.2  r42hc72bb7e_2             conda-forge/noarch            Cached
  + r-remotes                             2.4.2  r42hc72bb7e_1             conda-forge/noarch             416kB
  + r-rlang                               1.0.6  r42h526691d_1             conda-forge/linux-aarch64        2MB
  + r-rmarkdown                            2.20  r42hc72bb7e_0             conda-forge/noarch            Cached
  + r-roxygen2                            7.2.3  r42he0e9005_0             conda-forge/linux-aarch64      793kB
  + r-rprojroot                           2.0.3  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-rstudioapi                           0.14  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-rversions                           2.1.2  r42hc72bb7e_1             conda-forge/noarch              74kB
  + r-sass                                0.4.5  r42he0e9005_0             conda-forge/linux-aarch64        2MB
  + r-sessioninfo                         1.2.2  r42hc72bb7e_1             conda-forge/noarch             204kB
  + r-shiny                               1.7.4  r42h785f33e_0             conda-forge/noarch            Cached
  + r-sourcetools                       0.1.7_1  r42he0e9005_0             conda-forge/linux-aarch64       55kB
  + r-stringi                            1.7.12  r42h7e26fe9_0             conda-forge/linux-aarch64      887kB
  + r-stringr                             1.5.0  r42h785f33e_0             conda-forge/noarch            Cached
  + r-sys                                 3.4.1  r42h8e445f0_0             conda-forge/linux-aarch64       52kB
  + r-systemfonts                         1.0.4  r42h7b509ea_1             conda-forge/linux-aarch64      290kB
  + r-testthat                            3.1.6  r42he0e9005_0             conda-forge/linux-aarch64        2MB
  + r-textshaping                         0.3.6  r42haae8ff6_4             conda-forge/linux-aarch64      115kB
  + r-tibble                              3.1.8  r42h8e445f0_1             conda-forge/linux-aarch64      698kB
  + r-tinytex                              0.44  r42hc72bb7e_0             conda-forge/noarch             142kB
  + r-urlchecker                          1.0.1  r42hc72bb7e_1             conda-forge/noarch              52kB
  + r-usethis                             2.1.6  r42hc72bb7e_1             conda-forge/noarch             801kB
  + r-utf8                                1.2.3  r42h4fed366_0             conda-forge/linux-aarch64      148kB
  + r-vctrs                               0.5.2  r42he0e9005_0             conda-forge/linux-aarch64        1MB
  + r-waldo                               0.4.0  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-whisker                             0.4.1  r42hc72bb7e_0             conda-forge/noarch              82kB
  + r-withr                               2.5.0  r42hc72bb7e_1             conda-forge/noarch            Cached
  + r-xfun                                 0.37  r42he0e9005_0             conda-forge/linux-aarch64      405kB
  + r-xml2                                1.3.3  r42h9277e5c_2             conda-forge/linux-aarch64      199kB
  + r-xopen                               1.0.0  r42hc72bb7e_1004          conda-forge/noarch              30kB
  + r-xtable                              1.8_4  r42hc72bb7e_4             conda-forge/noarch            Cached
  + r-yaml                                2.3.7  r42h4fed366_0             conda-forge/linux-aarch64      119kB
  + r-zip                                 2.2.2  r42h8e445f0_0             conda-forge/linux-aarch64      170kB
  + readline                              8.1.2  h38e3740_0                conda-forge/linux-aarch64      312kB
  + sed                                     4.8  ha0d5d3d_0                conda-forge/linux-aarch64      289kB
  + sysroot_linux-aarch64                  2.17  h43d7e78_13               conda-forge/noarch              35MB
  + tk                                   8.6.12  hd8af866_0                conda-forge/linux-aarch64        4MB
  + tktable                                2.10  hcd05d48_3                conda-forge/linux-aarch64       90kB
  + xorg-kbproto                          1.0.7  h3557bc0_1002             conda-forge/linux-aarch64       27kB
  + xorg-libice                          1.0.10  h3557bc0_0                conda-forge/linux-aarch64       61kB
  + xorg-libsm                            1.2.3  h965e137_1000             conda-forge/linux-aarch64       27kB
  + xorg-libx11                           1.7.2  h3557bc0_0                conda-forge/linux-aarch64      983kB
  + xorg-libxau                           1.0.9  h3557bc0_0                conda-forge/linux-aarch64       14kB
  + xorg-libxdmcp                         1.1.3  h3557bc0_0                conda-forge/linux-aarch64       20kB
  + xorg-libxext                          1.3.4  h3557bc0_1                conda-forge/linux-aarch64       54kB
  + xorg-libxrender                      0.9.10  h3557bc0_1003             conda-forge/linux-aarch64       34kB
  + xorg-libxt                            1.2.1  h3557bc0_2                conda-forge/linux-aarch64      392kB
  + xorg-renderproto                     0.11.1  h3557bc0_1002             conda-forge/linux-aarch64       10kB
  + xorg-xextproto                        7.3.0  h3557bc0_1002             conda-forge/linux-aarch64       28kB
  + xorg-xproto                          7.0.31  h3557bc0_1007             conda-forge/linux-aarch64       75kB
  + xz                                    5.2.6  h9cdd2b7_0                conda-forge/linux-aarch64      441kB
  + zlib                                 1.2.13  h4e544f5_4                conda-forge/linux-aarch64      101kB
  + zstd                                  1.5.2  h44f6412_6                conda-forge/linux-aarch64      399kB

  Summary:

  Install: 188 packages

  Total download: 279MB

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

</details>

I'm going to close this and the PR out, but feel free to share any more feedback.

**Closed as completed by mfansler** 2023-02-08 03:57 UTC
Labels: question

**Comment by mathbunnyru** [comment] 2023-02-08 10:27
Thank you @mfansler.
I restarted our pipeline: https://github.com/jupyter/docker-stacks/actions/runs/4122939982

Also, I will try to eliminate the differences between x86_64 and aarch64 images.
If you can, please, take a look here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4078
